### ISSUE TITLE
Possible issue in data update

### ISSUE THREAD

**Issue by karoliskoncevicius** [trendecon/data#12]
Some monthly and weekly raw data (under `data/ch`) were last updated 2 months ago.

Need to figure out why that is.

**Comment by angelicambg** [comment]
As far as I remembered, we didn't want to store monthly or daily since we can have it with the function `ts_frequency()`, but @christophsax can correct me if I'm wrong.

**Comment by christophsax** [comment]
We didn't want to store the redundant low frequency data of the final output. But this data are the monthly and weekly series drawn from google. They are not the same, and are combined in a later step.

So, they should be kept.

**Comment by karoliskoncevicius** [comment]
@christophsax this seems to be coming from quite a serious bug in `proc_keyword_latest()`:

      enhance_keyword <- function(data, keyword, geo, suffix){
        old <- read_keyword(keyword, geo, "d") %>%
          mutate(n = as.integer(n))
        new <- aggregate_windows(data)
        write_keyword(aggregate_averages(old, new), keyword, geo, "d")
      }

The function above is used for all - daily, weekly, and monthly. However "d" is hardcoded in the code. So whenever data for weeks or months is updated - it is written on top of daily files. As a result - weekly and monthly are never updated. As a result - daily is corrupted by averaging it with monthly and weekly values.

Need to figure out a good solution how to fix this one.
Let's talk more about it when you have some time?

**Comment by karoliskoncevicius** [comment]
@christophsax I redownloaded all the data and prepared indices from scratch again. Here is the result of my comparison between old data and new data

**Prepare the datasets** (one from original branch, and one from new branch)

    library(tsbox)
    library(readr)

    files <- c("clothing", "garden", "luxury", "mobility", "social", "travel", "trendecon", "fooddelivery")
    files <- paste0(files, "_sa.csv")
    files_org <- file.path("https://raw.githubusercontent.com/trendecon/data/master/data/ch/", files)
    files_new <- file.path("https://raw.githubusercontent.com/trendecon/data/dev_daily_update_issue/data/ch/", files)

    dats_org <- map(read_csv, files_org)
    dats_new <- map(read_csv, files_new)

**Compare the indices**

    plot_series <- function(ts, name) {
      plot(ts$time, ts$value, type="l")
      title(name)
    }

    par(mar=c(2,2,2,2), oma=c(0,0,2,0))
    layout(matrix(1:16, ncol=2))
    Map(plot_series, c(dats_org, dats_new), basename(c(names(dats_org), names(dats_new))))

    mtext("comparison between original (left) and new (right) data", 3, outer=TRUE, col="red")

![ts](https://user-images.githubusercontent.com/7273684/91981105-01f16880-ed31-11ea-8cff-2b0197114159.png)

It seems like the end is affected in some cases. Also the 3rd one - seems like PC sign got inverted (which is a separate issue that will be fixed next).

**Actual differences**

    plot_series_diff <- function(ts1, ts2, name) {
      plot(ts1$time, ts1$value-ts2$value, type="l")
      title(name)
    }

    par(mar=c(2,2,2,2), oma=c(0,0,2,0))
    layout(matrix(1:8, ncol=1))
    Map(plot_series_diff, dats_org, dats_new, basename(c(names(dats_org))))

    mtext("original series minus new series", 3, outer=TRUE, col="red")

![ts_diff](https://user-images.githubusercontent.com/7273684/91981241-2fd6ad00-ed31-11ea-8a28-7a072363a67d.png)

Indeed, seems like all of them show the biggest difference at the very end. I am not sure if there is a pattern. But maybe in the original data the difference was smoothed-out, compared to the one visible in the new set.

What do you think?

**Comment by christophsax** [comment]
Thanks a lot, @KKPMW! It makes sense that the main differences occur at the end.

The main differences I see:

- Rebound of 'garden' is much stronger now.
- Same for the 'trendecon' main series. 
- For luxury, it seems that the sign has switched

The differences in trendecon are surely the most relevant. Plotting again to show its significance:

``` r
library(tsbox)
library(tidyverse)
old <- read_csv("https://raw.githubusercontent.com/trendecon/data/master/data/ch/trendecon_sa.csv", col_types = cols())
new <- read_csv("https://raw.githubusercontent.com/trendecon/data/dev_daily_update_issue/data/ch/trendecon_sa.csv", col_types = cols())

ts_plot(ts_span(ts_c(old, new), "2019-07-01"))
```

![](https://i.imgur.com/E64X3mH.png)

<sup>Created on 2020-09-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

@angelicambg @uwethuemmel @ninamuehlebach @vzei @ronaldindergand @izmartinez what is you opinion? 

Should we write a methodological blog post on this? The implications are substantial: According to the revised trendecon main indicator, we are back to normal, while the current indicator still shows a slightly depressed economy.

Shall we wait with updating to the revised series until we have a blog post? I probably would not but go ahead.

What about luxury? I probably would drop it, rather than manually switch the sign - this is getting messy otherwise.


@vzei @ronaldindergand @izmartinez, since we talked about this recently: The current indicator is what you get if you look at daily data only. The revised takes into account the weekly and monthly series over the last months.

**Comment by karoliskoncevicius** [comment]
@christophsax 

RE PC sign: I submitted my proposal for a PC sign fix to the trendecon, will test it now. According to how I see it, every time series is prone to flip back and forth. So a robust dealing with the problem is in order (in my opinion).

RE changes between old and new: yup, your description makes sense. The problem was that month-old data was being integrated into the current day. With the COVID crisis this meant that the values at the level of the crisis were being dragged for longer than they should. And I think thats why we "saw" a lesser rebound.

**Comment by karoliskoncevicius** [comment]
@christophsax 

Pushed data prepared with additional PC-sign check step to the branch `dev_pc_sign_check`: luxury is back in order now. Same for Austria!

**Comment by angelicambg** [comment]
I also think that it would be better to update the series as soon as we can. Maybe we can add on "Latest News" that there have been some changes to the indicators and more information will be posted in the upcoming days. What do you think?

On the other hand, I think that these changes might affect Stefan's [post](https://github.com/trendecon/gtrendecon/issues/58), especially the 4th paragraph because indicators about food delivery as well as gardening don't remain as high as we thought. @SLegge2020 what do you think? I already have the post for the website but I haven't committed it to the repo yet.

**Comment by SLegge2020** [comment]
@angelicambg We can edit the respective sentence. What matters is that the data are correct and the text fits the data shown.

**Comment by christophsax** [comment]
I guess the best is if @KKPMW merges to the new data ASAP. Thanks!

**Comment by karoliskoncevicius** [comment]
@christophsax will try merging soon. Also some good news: the changes for trendecon/trendecon were merged, and so we can now confirm that those changes fixed the monthly/weekly update issue, and AT and DE started getting updated as well.

**Comment by karoliskoncevicius** [comment]
@christophsax merged.
