### ISSUE TITLE
Links in the table are invalid

### ISSUE THREAD

**Issue by christophsax** [trendecon/data#23]
They need to point to the updated location, as they do in the examples.

<img width="554" alt="image" src="https://user-images.githubusercontent.com/1390827/102476823-d3876700-405b-11eb-8a80-fc5728fb3e17.png">

**Comment by karoliskoncevicius** [comment]
@christophsax 

The problem with this is that Daily, Weekly, and Monthly data is not available currently for the constructed indices, only the individual keywords. I mentioned this in the original issue.

Added the links to the "sa" data for each keyword, and left these ones in place, but with a strike-through. I am not sure what the plan is - to add them later? to use keywords instead of indices? or to remove them?

**Comment by christophsax** [comment]
Let's drop them. We only have one entry per keyword - this makes the table easier to read.

Perhaps we should have section for CH, DE and AT.

**Comment by karoliskoncevicius** [comment]
1. Added the available data for DE and AT.
2. Dropped the daily/weekly/monthly data parts.
