### ISSUE TITLE
GHA error

### ISSUE THREAD

**Issue by pat-s** [trendecon/data#26]
https://github.com/trendecon/data/runs/2162944175?check_suite_focus=true#step:20:23953

@karoliskoncevicius Could you have a look? Thanks :)

**Comment by karoliskoncevicius** [comment]
The error appears quite random, occurs on different download each time, but always on the first fetch of daily data for some keyword.

I only found out that it might be related to the latest Ubuntu version and Curl: https://github.com/PMassicotte/gtrendsR/pull/384

But will have to check deeper, but leaving that for the next day.

**Comment by pat-s** [comment]
Thanks! Could very well be that it's random. Seen it for multiple days now, hence I created this issue.

Next time I should wait for like 7 days or so to really see if it persists.

**Comment by karoliskoncevicius** [comment]
Now running it manually on a mac, so far no error. If everything works I will manually upload the updated data to the repo so that we have values for the past week.

I suspect it is related to the newer Ubuntu version. I noticed these ticks in the past were notifying us about Ubuntu version being updated soon, and these errors increased in frequency after that. Will see if I can write an exception for this error.

**Comment by pat-s** [comment]
Switching to 18.04 could be a cheap solution. 
I will do so and see if it helps. 

Thanks for your effort!

**Comment by karoliskoncevicius** [comment]
Thanks, checking if it works on earlier version would be nice. If the issue persists then I will try to create an exception and see if re-trying would bypass the error.

Just ran everything on a mac and no error - uploaded all the updated data manually.

**Comment by pat-s** [comment]
Ubuntu 18.04 did the trick - thanks!

**Comment by karoliskoncevicius** [comment]
Really good to hear. Thanks a lot for the update and changes.
